server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    api:
      path: /api/**
      url: http://localhost:8181/api
    auth:
      path: /oauth/**
      url: http://localhost:8181/oauth/
    users:
      path: /users/**
      url: http://localhost:8181/users
    secure:
      path: /secure/**
      url: http://localhost:8082/secure
