server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    api:
      path: /api/**
      url: http://localhost:8181/api
    auth:
      path: /oauth/**
      url: http://localhost:8181/oauth/
    secure:
      path: /secure/**
      url: http://localhost:8082/secure
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka