server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    api:
      path: /api/**
      url: http://localhost:8181/
    auth:
      path: /oauth/**
      url: http://localhost:8181/oauth/